spring:
  profiles:
    active: local
  application:
    name: business-app1
  config:
    import: "optional:configserver:"
  cloud:
    config:
      fail-fast: true #true로 할경우 config server와 통신실패시 바로 종료
      username: user
      password: password
      discovery:
        enabled: true
        serviceId: config-server
    consul:
      discovery:
        healthCheckPath: /actuator/health
        register-health-check: off
management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: false
      show-values: ALWAYS

foo: local-foo
test: local-test

logging:
  level:
    root: info
    web: debug

server:
  port: 8080

encrypt:
  key: mysecret