spring:
  application:
    name: gateway
  cloud:
    consul:
      discovery:
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        register-health-check: off
    gateway:
      routes:
        - id: need-auth
          uri: lb://business-app1
          predicates:
            - Path=/need-auth/**
          filters:
            - AuthFilter
            - RewritePath=/need-auth/?(?<segment>.*), /$\{segment}

server:
  port: 80

logging:
  level:
    root: info
    web: debug