spring:
  profiles:
    active: local # ????? ???
    group:
      local: db,oauth
  application:
    name: auth-server
  cloud:
    consul:
      discovery:
        healthCheckPath: /actuator/health
        register-health-check: off
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
    web: debug

server:
  port: 9999
