spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 733339714836-48kn30saeoopdpsf5faocq1icjfg11fl.apps.googleusercontent.com
            client-secret: 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
            client-name: oauth2-app-dev
            redirect-uri: http://localhost:9999/login/oauth2/code/google
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: profile,email