spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      schema-locations: classpath:h2/schema.sql
#      data-locations: classpath:h2/data.sql
      mode: always
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console